on:
    workflow_run:
      workflows: [Build homolog]
      types: [completed]
  
jobs:
    on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - run: echo 'The triggering workflow passed'
    on-failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - name: Print logs
          env:
            GH_TOKEN: ${{ github.token }}
            GH_REPO: ${{ github.action_repository }}
          run: |            
            # echo "gh run view --job=$job_id_teste --log | grep error"
            # echo "gh api \
            # -H "Accept: application/vnd.github+json" \
            # -H "X-GitHub-Api-Version: 2022-11-28" \
            # /repos/${{ github.repository }}/actions/jobs/${{ needs.merge-branch.outputs.job_id }}/logs"
            # gh api \
            # -H "Accept: application/vnd.github+json" \
            # -H "X-GitHub-Api-Version: 2022-11-28" \
            # /repos/${{ github.repository }}/actions/jobs/${{ needs.merge-branch.outputs.job_id }}/logs

    dump_contexts_to_log:
      runs-on: ubuntu-latest
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ github.event.repository.id }}
          run: echo "$JOB_CONTEXT"