on:
    workflow_run:
      workflows: [Build homolog]
      types: [completed]
  
jobs:
    on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Get issue id
          env:
            GH_TOKEN: ${{ github.token }}
            GH_REPO: ${{ github.repository }}
          run: | 
            url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} -X DELETE)
            echo $url

    on-failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - name: Print logs
          env:
            GH_TOKEN: ${{ github.token }}
            GH_REPO: ${{ github.repository }}
          run: |
            log_comment=$(gh run view ${{ github.event.workflow_run.id }} --log | grep error)            
            echo "$log_comment"
            issue_number=$(gh run view ${{ github.event.workflow_run.id }} --log | grep issue | grep -o '[0-9]*$')
            echo "$issue_number"
            gh issue comment $issue_number --body "$log_comment"