on:
    workflow_run:
      workflows: [Build homolog]
      types: [completed]
  
jobs:
    on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Get issue id
          env:
            GH_TOKEN: ${{ github.token }}
            GH_REPO: ${{ github.repository }}
          run: | 
            echo 'The triggering workflow passed'
            issue_id=$(gh run view ${{ github.event.workflow_run.id }} --log | grep issue | xargs -r0 grep -x -E '[[:digit:]]+')
            echo "$issue_id"
            # gh api repos/${{ github.repository }}/actions/runs/${{ github.issue.number }} -X DELETE >/dev/null
    on-failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - name: Print logs
          env:
            GH_TOKEN: ${{ github.token }}
            GH_REPO: ${{ github.repository }}
          run: |            
            echo "gh run view ${{ github.event.workflow_run.id }} --log | grep error"
            gh issue comment 12 --body "Hi from GitHub CLI"
            # echo "gh api \
            # -H "Accept: application/vnd.github+json" \
            # -H "X-GitHub-Api-Version: 2022-11-28" \
            # /repos/${{ github.repository }}/actions/jobs/${{ github.event.workflow_run.id }}/logs"
            # gh api \
            # -H "Accept: application/vnd.github+json" \
            # -H "X-GitHub-Api-Version: 2022-11-28" \
            # /repos/${{ github.repository }}/actions/jobs/${{ github.event.workflow_run.id }}/logs

    dump_contexts_to_log:
      runs-on: ubuntu-latest
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ github.event.workflow_run.id }}
          run: echo "$JOB_CONTEXT"